---
- hosts: 127.0.0.1
#  become: true  # use sudo
  remote_user: root
  tasks:
  - name: Add EPEL repository needed for pip (Centos7)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://dl.fedoraproject.org/pub/epel/7Server/x86_64/
      enabled: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: Add EPEL repository needed for pip (Centos6)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://dl.fedoraproject.org/pub/epel/6Server/x86_64/
      enabled: yes
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: yum install needed packages
    yum: name={{ item }} state=present disable_gpg_check=yes
    with_items:
      - git
      - mod_wsgi
      - mod_ssl
      - python-pip
      - pwgen
  
  - name: install needed pip packages (service dependancies)
    pip: name={{ item }} state=present
    with_items:
      - flask  
      - configparser
      - flasgger
      - configi
      - google-api-python-client
      - progress
      - cmd2

  - name: create dsds group
    group:
      name: dsds
      state: present

  - name: create dsds user
    user:
      name: dsds
      state: present
      shell: /bin/bash
      group: dsds

  - name: create subfolder for dsds code
    file: path={{ item }}
          state=directory
          owner=dsds
          group=dsds
          mode=0775
    with_items:
         - /opt/client
         - /home/dsds/.ssh
   
  - name: deploy github key for dsds user
    copy:
      src: ../files/dsds-git.pem
      dest: /root/.ssh
      owner: root
      group: root
      mode: 0700

  - name: upload ssh config for dsds - github communication
    copy:
      src: ../files/config
      dest: /root/.ssh/
      owner: root
      mode: 0644

  - name: clone dsds-client code 
    git:
     repo: 'git@github.com:EMBL-EBI-TSI/DSDS-Client.git'
     dest: /opt/dsds-client/
     version: devel
     clone: yes
     accept_hostkey: true
     update: no

  - name: setup DSDS server hostname 
    lineinfile:
      path: /opt/dsds-client/dsds-client-cmd.py
      regexp: '^server_host = '
      insertafter: '#server_host'
      line: 'server_host = "192.168.3.22"'

  - name: setup DSDS server port
    lineinfile:
      path: /opt/dsds-client/dsds-client-cmd.py
      regexp: '^port = '
      insertafter: '#port'
      line: 'port = "443"'
